Attempt: 1
Today's date: 2023-06-30 08:55:03.273569
User is not enable TOTP! Please enable TOTP through mobile or web
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 204, in login_in_aliceblue
    userSessionID = verifyTotp['userSessionID']
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Attempt: 2
Today's date: 2023-06-30 08:55:11.297230
User is not enable TOTP! Please enable TOTP through mobile or web
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 204, in login_in_aliceblue
    userSessionID = verifyTotp['userSessionID']
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Attempt: 3
Today's date: 2023-06-30 08:55:19.318353
User is not enable TOTP! Please enable TOTP through mobile or web
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 204, in login_in_aliceblue
    userSessionID = verifyTotp['userSessionID']
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Attempt: 4
Today's date: 2023-06-30 08:55:27.221339
User is not enable TOTP! Please enable TOTP through mobile or web
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 204, in login_in_aliceblue
    userSessionID = verifyTotp['userSessionID']
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Attempt: 5
Today's date: 2023-06-30 08:55:35.146571
User is not enable TOTP! Please enable TOTP through mobile or web
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 204, in login_in_aliceblue
    userSessionID = verifyTotp['userSessionID']
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
The script has some errors. Please Check !!!
{"ok":true,"result":{"message_id":368,"from":{"id":5994380365,"is_bot":true,"first_name":"trialbot","username":"traderstrialBOT"},"chat":{"id":-367108102,"title":"Traders cafe","type":"group","all_members_are_administrators":true},"date":1688095538,"text":"Can't Login. Please Check !!!"}}Attempt: 1
Today's date: 2023-07-03 08:55:02.743452
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 206, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 2
Today's date: 2023-07-03 08:55:10.350077
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 206, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 3
Today's date: 2023-07-03 08:55:17.945576
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 206, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 4
Today's date: 2023-07-03 08:55:25.634215
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 206, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 5
Today's date: 2023-07-03 08:55:33.228842
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 283, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/NiftyStrategy/Brokers/DailyLogin.py", line 206, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
The script has some errors. Please Check !!!
{"ok":true,"result":{"message_id":372,"from":{"id":5994380365,"is_bot":true,"first_name":"trialbot","username":"traderstrialBOT"},"chat":{"id":-367108102,"title":"Traders cafe","type":"group","all_members_are_administrators":true},"date":1688354734,"text":"Can't Login. Please Check !!!"}}Attempt: 1
Today's date: 2023-07-04 08:55:02.581790
Login Successfully
Session id for BY1424: crOqpn69hK5Rp3Hzh43nSpnsXNcfXaxRqr9XuOVEq6v0chKvv5VOYOczQMrOn0bopYHI7hEqcmpyQb9h3FGKV9mEDdBDMMaWR4qU2KkW9Zq1BPII6EBAfCBKHrvaF8bpFaPdz9aJCARKM4J3A1I7bGSBy3ClQ3lz17kg1sUbDJjPnaMpcdqef8fz5NtKbtRqyQhkmWQEhSFqQvufOKtEaxKKWJZ2pk76DUWnizQA5O5mYNPeP1a4QLFl0EuEhAYB
Login Successfully
Session id for 929016: K2X7iRVVxvcLM7jYkQijDEhCBnPX1SIsbNvpam8YDZIp3LM4sRj442jqFAKOvIJNHr1yPtI6yWWK3qykd1gHPKEB207mZIVy3F4jqhLjqhzFVHeEoJRj4DWEjXuEr2BCNoUjOVUG44FjG1XiZzLYXTJRk6IG4pqPgk8J9K4eeEBhWxjCAYBrtsmqEFVZbVFH8BSg3YCm8L8bW8sJP32qDIfM1TQfhihh0M3qGfCf6fQsQMCJgHnSAalfpDj9yoCt
Login Successfully
Session id for 110958: SW5DrIbQRKaoYY1o273TQekbCZrlECgcxtcb8av7pOSH1430KPffsACbiXe977dPGIEAMte2TdtTYI8fIMG8U7Dqf8DfBJVqHIWuh0mjoE4foDzJROROxyWdSdgccUbGg0A3Em1RYf4OGJmD2nOdcgLSaGask4BzSm8MWWBY1Xo42czHFic3t7d4mf00RKRhjJvStG2U2XQGMPp9uYR9P8KBMyBcr2irMtBIh2tFGyIzSsh7GBq4gLV6UZF4flJA
Login Successfully
Session id for 924446: BJhl6TkkAfX4Wf4dRPSGDYUIRe5HjHfKTt2stvVa6NDGcp9s9OW98XknixOBFtHPJlDFzIRSx2lnazFQjZqZTkLMFB3xvU6EJM12Hp2dG5cNxtEA5Pijc5Qp0ddWXK1IDdL1ZioxI0Pi4HsWbZLUKzXizFv8Hoqo64kBtBkdTtLSOP6r8pLAPnCGynhfukf8yUMLG5dytr97DaR6iEBI1vfPnTVpMO9UmUqiakhD5eCAZpkZcsWcZKdfZSNcANFS
Login Successfully
Session id for 935347: k1eybyaBritnEr3uDoX3XjrAE0pfP2gfdsFKunZFAOPClNntc0HPHT5jWAs0MIaZ3ojvSVqBKoF7Jy8iX6Hd6sv1Vz21Ri4Ix3je0eCOqqQhCEzWvfi8x1S8oUo0daK3FihHfTSU82kslFTbI15qGMko4V0WdcikDYXF52nuoWD1gh0ZHkDnfmOMPfs89CSZ5iYsOD09YuRAyal1c7oGD9TxWZoJ4OKmuBW7xToKmVKH726t67Zs9X6IO9KjTzAB
Login Successfully
Session id for 935325: G7fRKJmI0mkW6HR4yFoQocRdclq6uZoDYATuxiAYUnyPf6Pk7TdzjkGkXY8qFtQPXFUNzjQdEBrC0ydM18X1HQoUWId8CmzltPFt3N0jzLQ3AA3x1Gr7eDniXQT3V1kpbd731jCiZnfklnlxAT37d0yaQetKgFm5s9Ny2gHgoWPjIEY6cVDAs3iGSrr0gcfQ4NGu8kTLYXo43zSJ0tImhhSPjcFqGrnGH8Fd3gObjKXK6br8vVW4XqE9m0QrKBkc
kite_access_token for YY0222: IQsggOcjChoJ26Fho4gAC3OkYhskoqXQ
Program started successfully
Attempt: 1
Today's date: 2023-07-05 08:55:03.416842
Login Successfully
Session id for BY1424: UCLXdTBX5GqXpI69UVJL9PnMQGsbs7aTypiuz9iSyxNjWFsEqUKefKql2EqHfdHdo64v1sI6uXy8hl6N2HirydSnPhWSpj17vqR3bBnnEWZ9LaD6n0BOkTylnns8jlabA07pMToUY7Tj479atsKHuS1SJCFp9SiDaKuQsrz8MxLIU5kVDKYHWAxeCRfN35sVlDjqMs0RdziRKCRZFRNc9D54rV5kA6DWAEEioP3yQn88QOZgnOAaaa1kFmzblzR8
Login Successfully
Session id for 929016: fBIghiyDzJSLkNSgngQMMW9IW2dlkWYceKGKfTcHe0EaqyqEKnHS2FRdB4hVKayRK5amdNhrcODx6vdyBr4GP3Ez4KbhWlVy6V7FUBQiDHDFkoPPdStJdcB8oWMqPMspgyMqRyfvbN1nulqDRPF5fp0Dt3LkHPy4l3yIpZNjsT7L8BeZXy31qbzC4ALMDknxreIT1WmbHHWE4q9hyYbHFzIC44Hze7szLTMaB1HrBlehGoyc3Aydmttc0eoJvLV5
Login Successfully
Session id for 110958: XAHNdfiPeSQDv4WyzkFHqGR8S2RQHP9nDMKxGVszztFVupoDEVn4vbqXQJixRtHKv8B1Rqufl0A8zeuhbDSTSEAThXgTtW5YFTgna49iFJIcXhLfV65L5x91rXfnYqMxalOzlDvNy7g8EWjRWJKmYd7mJQXgkkWoAqGZavpgcxIV0E7cBEpGWJvfqXejqnlRnonBn8VNkefPvHhtLaPzGJE6OC5CoRmuVJqTZs9kNKAMR0GJfkjvUNvilT6Gib8r
Login Successfully
Session id for 924446: rvKiWQsjEJLSOhetSCezfYoP43yGHYYVfzFud35sUglnJCi54g0BApq1aUydBBhpNULA0jSoj6njWFoQrvmZkKTYsRgJme5lOEWmWLp5ZKvcEHBWeGKdqpE5iq2cHden4gIzy8svkNqrLAKoFyJoizfK2E3WrCbx1g0Di7AQt4otNrTt5OhUvR2XaDxsfyYbB811S1ZJRPTmQAUjxAn7EUzmzC0v2OzrgCnxxAxP7fFqUFpOjjFrpFlpX0Yu1Bez
Login Successfully
Session id for 935347: 7oumiW9ReKJ5h7OdTFDqEAh87hiYahB4nIFraTu46jUWmSRfUHU7DrRZ2Ud90yMWUNYOpipXqpRKpsbFPVSOf7H24nF71pIq3qqbH1ZPcLP1gXTc1DpAgC5sXbyAs8T6teFquTCJeuojI9h0HI69trKKLbxdHyo12uPKoiOMQndyCtA9kbOvC54y3tsRRve1MtR1A3mKKpVM5hHCq8k9rg1XsCRRLTOclQNAtzBSaypfb8rjoLBc6QVUqXSC6qHJ
Login Successfully
Session id for 935325: 7XrtZzHJUeI6Q86U1Eg6udtUq9VX1cMTWP8Wddffa42VhjFqq9CUinTFV2dNqSdneUeZCVeVYUqz2chyWNojzUp0gN5U1yHcfIoI0pbv9Z8pv5P2Sp8aD1mFjK20gsGS176QfZiqdre5Bm7KvPRXIOoaHJsPMxzNtLRbEnBneTAeTQMtNySYUD93dggphXbJQmBjKN75Y27tjYhchWUyGXfiHSLMPtzC5vlthpAthWgHQLshnzgBoir4XQGK6vXv
kite_access_token for YY0222: ddm42QXGcmvCDUP9r3Ha1m8JBp12jJCr
Program started successfully
Attempt: 1
Today's date: 2023-07-06 08:55:03.499721
Login Successfully
Session id for BY1424: m9nGcJTvBVH0KR4LDQIQsfuYirjd8yCMSN0s5oNxmd9AfdflkENshFx4psaQQASTa5ujR4xu0T6KsLDIdJKa6N2gvzzKSOB9jUis5SBp0QIGxzaIF2XAdggJa4Epim6ozJ3Oqetv5mcs7Tk1jk6soW6qg5mA4VlLutTmsm81pskddiszmYGkIBHaoUYhZMy3Ay35z7zi8r2neZC2a7GiGP5EvNOtSoZCNWMRfTF2cGmgemkR74zjEenWLMnEX66a
Login Successfully
Session id for 929016: nzvyYjpaiDKuCi8kDm4LVtvsPYythAUep11z9I30un5NSIgoYVpKLhU0QuLHCkjT4yuzrrVCFUeJgpI5pgNX9g6BYlM5UmGxv6z6ciDLW1bDGESPBPz7K0TgSGebQUVIZ2a1B5jH7LMvNGE8uFHRshm97ikzmCRziddbAsc3dVll7b7eUGtADVENNuNdS4SCt8nzaZAi8YFEhQxTjTvAjZTqtRJnDt4FKufpUmOaRX4hD7sy17VvXdBJiy2nuEC7
Login Successfully
Session id for 110958: 51bLjKKgfBcOOuNrBeijcq3Xy2JsDY9UQyjmGYEWrPvjiQjqeOL1Dd6U53NY3W0tIXb1gRSYj2aPaILQBISRDnrG0U0S10ie9a7psTgAPkHjhc3VWPCCyHITq1agbcUFRxdqkEUQm9llSvZq4N711iCWcKOk4jUxs4baZRV0rZdFGDYBaqHQsP0fMig4ArHOu3q8WEHXPyf0B4obUlYgxO69sWZeB7dWAGrU0696F1Idv4YUNOqD5j0FHp0BWnDf
Login Successfully
Session id for 924446: 9vUHS4Yz2tOi3uIXJNBh6PNtKE7G2RLeU6jPyNcMdAQuR8CXmBdSycnhvMM42AhcrkSNgpjmlbC9oLOWJXCZXXUgi6Dbx1bCW6sxOxMSMnZs7cei9njJVBgGe9FoKcOya5liV39maQQuqN8M7xRmGlxjjLYCIelcv6l0JFlZCVjUpbdxfSXLIEe8so43Xl93aYbCxaUMMZa5tu9xFyXXDGQd4soBl9jrCr10PpEEAYruvEa9AtCajoxUs57akZvg
Login Successfully
Session id for 935347: CLmqaQ80pdSKkMDbHqSZdyNQ2IzRBTbD7pD0p9iTjF8b76tlBXW0Z9Cgs2THKrJO01nLeOssqhbtJmpEpLNqDmjQgI9GmJMXLT2fv5eK6Yl0Rj0norJ6O6LGtjLAdUWudxpIz9A9lPtpfORaIn5BnKlulvRdW3u4FpZHLFcoVqmKuV8iGDGOhGttDuRD3i53mZzHDx8s3stG2f8or5vUDjlukCbz2mrejT5i0XKX3sNaxvkbMNMp8bXuElqaTdyO
Login Successfully
Session id for 935325: AnzSoaWH7ZqSrmjkH5CNORBZiZJv5M8DMxVpgoSCPVbOMik8Bo7R7iLGiutivYDKncWTbtr65m6i7FOr8eQ9IRHRmE7cj1TQhFdNSNPJKrQtTM8qtMCXAaYi8eQZ5BBdQmBVJt0lC8FVZyubclz5Fqzz98Z1c4cdUqgxkFWGxfAvqmXIt3hnnS0J5tpfuzfCZo6U93W3BRPy77WkiDkhxk2b69Tkc5YYMdj8CGkxJNxWSAVmazZLoggXxn4a435u
kite_access_token for YY0222: CbAzIkAuJXC0xjTXy07mJuImHeWuEFQW
Program started successfully
Attempt: 1
Today's date: 2023-07-31 08:55:03.150389
Login Successfully
Session id for 929016: nthFGmYOyDlZB3dBEv6JbPnbSHyR3P7Ub2OY6Z04bDYM6RHr7i0qQvXbXOFzEc3TH2i21r9rKOmPG8OAFPoDhCuuLhi3AP1YxX1DKcaItEMKbvJUdCRocdYkO9aq0NmhuAjr79Hiz0XLih3vQ9q1lozWfE8kkuBd7GhTr0Kpj7uOg0bZFdRj26MbIJmCzRedeRp9yHk4LDlWLjEWgeZlXcGnxPooPL5W3BKq8atEn3NT2Z0If5lm3Vvn5ZIeaFsH
Raw quantity: 396.5068333333333, Quantity: 350
Raw quantity: 142.74246, Quantity: 135
Raw quantity: 396.5068333333333, Quantity: 360
Login Successfully
Session id for 935325: LuzE8qW6DiEZ6bKfiNnoHU6Xi2cQEv4vPqqohibUUE21GWpVuoks4bQZ4oEEefKdFr68Qnx9XvqAMkNqhs4eYDpGlvBNhHnIdCmsgzOjPzVIasnaUpxiqvckteWqgvDUQJ13ksKeT1a2D6s2rCAbZVpxvozJFmfTS6CIgVD9oK55MBy62SsZoUrRjzA0vid6GIuA6LihcKDYfUbgz6plDNl2Z4NSct9FOr4NjMhrNKSbaTXjnnDB8ULhufrJu7T4
Raw quantity: 46.76435, Quantity: 0
Raw quantity: 16.835166, Quantity: 15
Raw quantity: 46.76435, Quantity: 40
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 296, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 220, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 2
Today's date: 2023-07-31 08:55:12.510631
Login Successfully
Session id for 929016: nthFGmYOyDlZB3dBEv6JbPnbSHyR3P7Ub2OY6Z04bDYM6RHr7i0qQvXbXOFzEc3TH2i21r9rKOmPG8OAFPoDhCuuLhi3AP1YxX1DKcaItEMKbvJUdCRocdYkO9aq0NmhuAjr79Hiz0XLih3vQ9q1lozWfE8kkuBd7GhTr0Kpj7uOg0bZFdRj26MbIJmCzRedeRp9yHk4LDlWLjEWgeZlXcGnxPooPL5W3BKq8atEn3NT2Z0If5lm3Vvn5ZIeaFsH
Raw quantity: 396.5068333333333, Quantity: 350
Raw quantity: 142.74246, Quantity: 135
Raw quantity: 396.5068333333333, Quantity: 360
Login Successfully
Session id for 935325: LuzE8qW6DiEZ6bKfiNnoHU6Xi2cQEv4vPqqohibUUE21GWpVuoks4bQZ4oEEefKdFr68Qnx9XvqAMkNqhs4eYDpGlvBNhHnIdCmsgzOjPzVIasnaUpxiqvckteWqgvDUQJ13ksKeT1a2D6s2rCAbZVpxvozJFmfTS6CIgVD9oK55MBy62SsZoUrRjzA0vid6GIuA6LihcKDYfUbgz6plDNl2Z4NSct9FOr4NjMhrNKSbaTXjnnDB8ULhufrJu7T4
Raw quantity: 46.76435, Quantity: 0
Raw quantity: 16.835166, Quantity: 15
Raw quantity: 46.76435, Quantity: 40
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 296, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 220, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 3
Today's date: 2023-07-31 08:55:22.032359
Login Successfully
Session id for 929016: nthFGmYOyDlZB3dBEv6JbPnbSHyR3P7Ub2OY6Z04bDYM6RHr7i0qQvXbXOFzEc3TH2i21r9rKOmPG8OAFPoDhCuuLhi3AP1YxX1DKcaItEMKbvJUdCRocdYkO9aq0NmhuAjr79Hiz0XLih3vQ9q1lozWfE8kkuBd7GhTr0Kpj7uOg0bZFdRj26MbIJmCzRedeRp9yHk4LDlWLjEWgeZlXcGnxPooPL5W3BKq8atEn3NT2Z0If5lm3Vvn5ZIeaFsH
Raw quantity: 396.5068333333333, Quantity: 350
Raw quantity: 142.74246, Quantity: 135
Raw quantity: 396.5068333333333, Quantity: 360
Login Successfully
Session id for 935325: LuzE8qW6DiEZ6bKfiNnoHU6Xi2cQEv4vPqqohibUUE21GWpVuoks4bQZ4oEEefKdFr68Qnx9XvqAMkNqhs4eYDpGlvBNhHnIdCmsgzOjPzVIasnaUpxiqvckteWqgvDUQJ13ksKeT1a2D6s2rCAbZVpxvozJFmfTS6CIgVD9oK55MBy62SsZoUrRjzA0vid6GIuA6LihcKDYfUbgz6plDNl2Z4NSct9FOr4NjMhrNKSbaTXjnnDB8ULhufrJu7T4
Raw quantity: 46.76435, Quantity: 0
Raw quantity: 16.835166, Quantity: 15
Raw quantity: 46.76435, Quantity: 40
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 296, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 220, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 4
Today's date: 2023-07-31 08:55:31.363887
Login Successfully
Session id for 929016: nthFGmYOyDlZB3dBEv6JbPnbSHyR3P7Ub2OY6Z04bDYM6RHr7i0qQvXbXOFzEc3TH2i21r9rKOmPG8OAFPoDhCuuLhi3AP1YxX1DKcaItEMKbvJUdCRocdYkO9aq0NmhuAjr79Hiz0XLih3vQ9q1lozWfE8kkuBd7GhTr0Kpj7uOg0bZFdRj26MbIJmCzRedeRp9yHk4LDlWLjEWgeZlXcGnxPooPL5W3BKq8atEn3NT2Z0If5lm3Vvn5ZIeaFsH
Raw quantity: 396.5068333333333, Quantity: 350
Raw quantity: 142.74246, Quantity: 135
Raw quantity: 396.5068333333333, Quantity: 360
Login Successfully
Session id for 935325: LuzE8qW6DiEZ6bKfiNnoHU6Xi2cQEv4vPqqohibUUE21GWpVuoks4bQZ4oEEefKdFr68Qnx9XvqAMkNqhs4eYDpGlvBNhHnIdCmsgzOjPzVIasnaUpxiqvckteWqgvDUQJ13ksKeT1a2D6s2rCAbZVpxvozJFmfTS6CIgVD9oK55MBy62SsZoUrRjzA0vid6GIuA6LihcKDYfUbgz6plDNl2Z4NSct9FOr4NjMhrNKSbaTXjnnDB8ULhufrJu7T4
Raw quantity: 46.76435, Quantity: 0
Raw quantity: 16.835166, Quantity: 15
Raw quantity: 46.76435, Quantity: 40
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 296, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 220, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
Attempt: 5
Today's date: 2023-07-31 08:55:42.223626
Login Successfully
Session id for 929016: nthFGmYOyDlZB3dBEv6JbPnbSHyR3P7Ub2OY6Z04bDYM6RHr7i0qQvXbXOFzEc3TH2i21r9rKOmPG8OAFPoDhCuuLhi3AP1YxX1DKcaItEMKbvJUdCRocdYkO9aq0NmhuAjr79Hiz0XLih3vQ9q1lozWfE8kkuBd7GhTr0Kpj7uOg0bZFdRj26MbIJmCzRedeRp9yHk4LDlWLjEWgeZlXcGnxPooPL5W3BKq8atEn3NT2Z0If5lm3Vvn5ZIeaFsH
Raw quantity: 396.5068333333333, Quantity: 350
Raw quantity: 142.74246, Quantity: 135
Raw quantity: 396.5068333333333, Quantity: 360
Login Successfully
Session id for 935325: LuzE8qW6DiEZ6bKfiNnoHU6Xi2cQEv4vPqqohibUUE21GWpVuoks4bQZ4oEEefKdFr68Qnx9XvqAMkNqhs4eYDpGlvBNhHnIdCmsgzOjPzVIasnaUpxiqvckteWqgvDUQJ13ksKeT1a2D6s2rCAbZVpxvozJFmfTS6CIgVD9oK55MBy62SsZoUrRjzA0vid6GIuA6LihcKDYfUbgz6plDNl2Z4NSct9FOr4NjMhrNKSbaTXjnnDB8ULhufrJu7T4
Raw quantity: 46.76435, Quantity: 0
Raw quantity: 16.835166, Quantity: 15
Raw quantity: 46.76435, Quantity: 40
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 296, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 220, in login_in_aliceblue
    userSessionID = twoFa['userSessionID']
                    ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'userSessionID'
The script has some errors. Please Check !!!
{"ok":true,"result":{"message_id":888,"from":{"id":5994380365,"is_bot":true,"first_name":"trialbot","username":"traderstrialBOT"},"chat":{"id":-367108102,"title":"Traders cafe","type":"group","all_members_are_administrators":true},"date":1690773946,"text":"Can't Login. Please Check !!!"}}Attempt: 1
Today's date: 2023-08-01 08:55:03.279762
Login Successfully
Session id for 929016: kBmObM9OJkuOUMdnHVuXPrnqCS0YGnqFxBQiOCGBrO8xrECpZrGACK6tBvmaPgNFqdOg7rzKlHYerSYsKScZLGCT2iYBHbekf9sQWdjSNFnMeQsfsAZrBMJCoza0K0LBdzRamjrxRumEqxgHI1jUD4N56R4yTTNb6eg1fM3mpmtFKOQ9M0bVaupyUmLFxBrYd8WIMPOyIn5Sk4mTIjcy3zAuoyt6Tiavr6P6rH4nWlLPbYxLAAyCH9UxT6kgEsCV
Raw quantity: 336.6786785714286, Quantity: 300
Raw quantity: 108.77311153846155, Quantity: 105
Raw quantity: 336.6786785714286, Quantity: 320
1
None
Login Successfully
Session id for 935325: k6icKIXENyoWsF6iJuDtKMhQUj1Qx3appelmmmWMrFipSfoBWLgsEfY6c8Mn2YPxuQ37L5g1eNSndrmpfCMx8BsHmeqaD2J07Ot08XcXl0rZzyS4ioeMITNS1Ox1Pda2qv55HR3on1A8UkZXtFDKX9JUB1bspH3C7hmUhU1UKRgsnCk4ZIFtc2JyQGmLLFuaqcGAhfqmiyjrK6XH0zIJEIiOL3sfq6GmBVv5L35UnecW6sfpfWaqzVxXydaT2aZb
Raw quantity: 39.39072857142857, Quantity: 0
Raw quantity: 12.726235384615384, Quantity: 0
Raw quantity: 39.39072857142857, Quantity: 0
None
Login Successfully
Session id for 924446: xKxryKp9YsUySiN3Er2R7Nat23aGtSTCCVJNnJEVeyie8ZWyPg0sZR1Cse8lPnH9KPvxN9Ru9vM9dQhU4YJ55kjW8es6zp07tYyDoeCs5fWTs3s7YofRjRXkdMl5U8zfVDEpMyIkDcsc4tJxSXomAQYkKvxFqfcjMDGKdIs6rdu7EptpaASPUdPUqYMGGWI7JeIm0x7g7xpsPGo1LLsDGCVzMEO6WZYr5uptN5rSk3LvoVFLQVC4bLpxjvhJrhiq
Raw quantity: 66.96828571428571, Quantity: 50
Raw quantity: 21.635907692307693, Quantity: 15
Raw quantity: 66.96828571428571, Quantity: 40
None
Login Successfully
Session id for 935347: XMt3R30gPoaJtQicVlcD8Hyy92oKQbmEl07umkeXmDad1qWXXON0YjZQd0ySYyDyVuvpUoiY8gcaGcG9P1ZJbSLcnl01KoqTf2SvKNHi3MFZMAhZ76Qsm0uy0bid0zotxMCYefPGBl5RN1Ijtrosp2GqCMGnjRZIY8sMVFktFRS952YE5SW9R0530HV1MlCKp8SnYmRRNeb9MBsloVvHp9FDAjoU7M1NaMHxQEU9AXdV4Do7auGaJuxNSpsc6dRJ
Raw quantity: 68.0077380952381, Quantity: 50
Raw quantity: 21.97173076923077, Quantity: 15
Raw quantity: 68.0077380952381, Quantity: 40
None
kite_access_token for YY0222: PjO2xbA0WBiRNOXncXSc25Yi7EIxWYUI
Raw quantity: 1147.443761904762, Quantity: 1100
Raw quantity: 370.7126, Quantity: 360
Raw quantity: 1147.443761904762, Quantity: 1120
Raw quantity: 1147.443761904762, Quantity: 1100
Raw quantity: 370.7126, Quantity: 360
Raw quantity: 1147.443761904762, Quantity: 1120
9
None
None
Program started successfully
Attempt: 1
Today's date: 2023-08-02 08:55:04.215995
Login Successfully
Session id for 929016: KTUmMIJ4DJyfbI970KAPOku2DdgoPe9ZEPshvglr2Z8FG7tRl67HJzERGXpzoKcEKvhG9znrNRNxIlZPfPEExkRjDPsFXoNM3ARJhASgi9MpnLuxofiX5Msi5HDLM99NFzV22CmC1utmPvoqZ2ZsWJPn91igGylaMyNrPOjXNHXzo5AWsmiTRQuSATsqFNMahYUkqT1dBnVm3FnVutOQtUGW7f9NYPQUiMNXh9stz0XzU4ZjmkuGdAMa3ugalPUB
Raw quantity: 291.43, Quantity: 250
Raw quantity: 87.429, Quantity: 75
Raw quantity: 291.43, Quantity: 280
Login Successfully
Session id for 935325: IreAHPOOOMfZ5jEMu5sbtz2KKBov1fZN4QGfcgrd78j1mHL01StANezmSQS8LCMLRP6e57MrQmJyv5SikXCjAhKjvsZhPtpemnplMuLb47b3LyYgDGo2yRehVddTAFvkUomJZ9jSxyN0PZLfO121gmt9MkN1zSXlvQsg3Ajtv687B2XZMgTaZ7luM3vSJ7JYS44fy8SC4KJOY0WzZ07oZc2jroOMWodQoqIjWDOSxlKW1irpakN6PBdVje1DOFDn
Raw quantity: 33.182849999999995, Quantity: 0
Raw quantity: 9.954854999999998, Quantity: 0
Raw quantity: 33.182849999999995, Quantity: 0
Login Successfully
Session id for 924446: 4qbghAJD8Fjtzu8HrStlHcC5G2zpf3yXMFOY2RbERRK5sSY16o9PaycceIhFAM4QMev1LrLafykJTX4yamgv2t5R4aZUdgfknfWoSDpnE44ncYzPlyzr192ivKK035RKNFjhRobGBnMeSm80CTNP4Gn3I3xLoDq16AyDVHqIddB0nTKFFolayZUMkOg5qOxblWBaHYlOzxBRlTmYLmqXEXU6LQbm114aZi6CnQIto7KiRR47JU4o6KFTnpi1Fm8O
Raw quantity: 57.56134375, Quantity: 50
Raw quantity: 17.268403125, Quantity: 15
Raw quantity: 57.56134375, Quantity: 40
Login Successfully
Session id for 935347: onCgWol24k2omPSJfx6qB9ntEDc24ZAOby6BUMBNPihgRiSA0tRSoEEvJTrGy1t6V6Z5LrtM5jrQpCIzSq82igLFhcEeeN5ERiZv1e27y9q1VnTvDdQDGclLGVKtBpjUgkqPiYFR8DNff5LS6Bu8QzypzK1cV1DCE2vbb2Kmv6kenhhRQn8ppo7TYMmycMxx9CV6h1jSJ0aXJibPcYBt27UlIQRF05fxaQKPuNcicULXPYaVD5Yxh8thUZsxLZGN
Raw quantity: 58.413833333333336, Quantity: 50
Raw quantity: 17.52415, Quantity: 15
Raw quantity: 58.413833333333336, Quantity: 40
kite_access_token for YY0222: gqDaAs6oH3tv212Xv6TD07GiYVqLIWZX
Raw quantity: 991.7450833333334, Quantity: 950
Raw quantity: 297.523525, Quantity: 285
Raw quantity: 991.7450833333334, Quantity: 960
Raw quantity: 991.7450833333334, Quantity: 950
Raw quantity: 297.523525, Quantity: 285
Raw quantity: 991.7450833333334, Quantity: 960
Program started successfully
Attempt: 1
Today's date: 2023-08-03 08:55:03.936352
Login Successfully
Session id for 929016: I8yedFsj8cMLbcv4z6nveHTFcEKZ7F1IpTVHFAhr14NQSeD8EFHF89i3MkjMrYWgP1ngbU1XCfipLWLA1AOd8k4PCIB2evGbDCRbuvYNuXIgeo6sYeUrvv2xlO1YJn9EnDgP4HdB47scEzQ2aT13M1Ru71LbNEa62YVpxnbYEEXLatu6l3EX6CK90sJrZMOJR8bOkLDNT3Mc6Yjjl5ufd1vtuF2MYlXWBPmIHTKTA77Dhm54l1uykWVTmtrIY1eg
Raw quantity: 268.426452, Quantity: 250
Raw quantity: 74.56290333333332, Quantity: 60
Raw quantity: 268.426452, Quantity: 240
Login Successfully
Session id for 935325: fQo6IOeDyHX2bHaS4aCN9yIG8dsYCObGqR3s7Nx2o6BGaWGND7kNLDk7GdRpRsWk0SJ46fuhXlOIA6Ha7Ye73ro4cxR1fTqJtuv5W57sovv1Tlh4XLkZ9is7J8brVVybQ80ofZcJn0gHdxHGFEfJaSY8D10Vumeqpx2APSaLp8rUuPOSPpXQY1rKfYfpnHe9UusSnHnmDOEc0uTRqnJedxFbHl9Po0SNTUlGPpqqCHtO31B8ivxGEjdeUlaFBdbJ
Raw quantity: 28.998396000000003, Quantity: 0
Raw quantity: 8.05511, Quantity: 0
Raw quantity: 28.998396000000003, Quantity: 0
Login Successfully
Session id for 924446: KboRpgiHo2gXlB0H5pkXNGbdDSKiP1SyHfyl006sX763oFdIVBeJnnuqePWiiMlSSO53tDkitstcPtP9zGa6cIPAEmVZiWFekk1aA4bzZu9xHhRfmZXrlW0yEY7DxcMssqDspCRhUVlLGaTBNkQcVyeaubmGgui35zpmkCRNKk9nxULMETAa41n3Hsr0VXkZS4cm6ukJ2ng2Q1ArBdGVg4AB6sZrV5xOWozEi5P3y1WeU7WoWJVGRXWfekrHQfvZ
Raw quantity: 52.873720000000006, Quantity: 50
Raw quantity: 14.687144444444446, Quantity: 0
Raw quantity: 52.873720000000006, Quantity: 40
Login Successfully
Session id for 935347: 9L1sBBky8Ujv5OdEbBbWPholvjCMeC2KWCVK4GFtZHoBVon6ZmgSv4BYgJSFEdkmi8zMl5HrGuuiHoNlbApSZXskgb3QGfoUKnM4WYtoBUIqQlNe7ChTEA12JyXLyFMdh2LOSHMNKNG0G7Oky069bJhEEYZPkcmnIu99QJjyDmgD6RuW0A3FToVIQ4XOVvyHl5uTC0CattyftmPfKKFWah12kjeM1Hx5PsOhFlO8I9X1WGEQz8F2kl4cOGZ4AWZJ
Raw quantity: 64.03366000000001, Quantity: 50
Raw quantity: 17.78712777777778, Quantity: 15
Raw quantity: 64.03366000000001, Quantity: 40
kite_access_token for YY0222: 1mS3sAFTtT5UlEY8YKV7pQBEDQr1vynz
Raw quantity: 912.2900800000002, Quantity: 900
Raw quantity: 253.41391111111116, Quantity: 240
Raw quantity: 912.2900800000002, Quantity: 880
Raw quantity: 912.2900800000002, Quantity: 900
Raw quantity: 253.41391111111116, Quantity: 240
Raw quantity: 912.2900800000002, Quantity: 880
Program started successfully
Attempt: 1
Today's date: 2023-08-04 08:55:03.439387
Login Successfully
Session id for 929016: 5RTjLKn2b30Pn13XI3szJOhLQhukfDqxYiG9pOnCFJrSO3VESPWX1vKWzjOIFz77xn63c5fk76ibQNxAamN2oBfhdqKmLzME2t1DQFTKOMChJ7WpJrD0uM37zPT233yEE4TxKJ69vgcGOLIZGpZbVz1fES6Y1HUZ1nKtIKoJqkUQCYUgml1TpSVvjboGLSik2fvRTCJNgHcr1JhzIDhrz22V0Q8EQuXVSfskYhPvC0ZUQZOOWDUBuLPKD2uDtLWD
AmiPy strategy
50
Login Successfully
Session id for 935325: 54pD9z7SoGfvhQoW8u9Xc3Xtvb063OX3acEYCc1G4zm9bXTurfsKgkV5ykRIldPuf4hDPv6s93DqP31YtNzF7I7EJelAUcGnmmySVYz6ITUIYXkQClZK5gDa1sSaW93ZlqcH0ro50rCnEIAUNPQykJFx5dr5nPcLD8Uc9qqWIzd4oJUDXjEamg6uVCY6J6R0fZAlyDkKbj6cL5nqDQrEVJkWVhAceVkVeugSYD81aiCH19IpVjft11aj47n1guVY
Login Successfully
Session id for 924446: qvjjtAg9rrHiIiKcH2iExTsaXTAi58YBtSizFQkmMgKbZ8NVT4VTAvMcfNBZflg9S2OtGUmeBJdb85CHIkNekzf026aj9NH3pN9CNlKY5aUUyiqyvSNL7NnMxYcsmV7OUju7NASvGO5eaWEo1QbFfDuncQRH9WA56nhzbkgelusT5uepScOBOkDBI46ABMtL6EZQItZFh298fpAKHKkePlAzbIik0kScLlckYXjIGx0OuTln5iY2uX3uHCasAS4P
Login Successfully
Session id for 935347: jOiCxXfPVIQZm1bRX6ErI1834VzAsK3V71zGXsOd4UQQK0sZCMOgxmxQtQkDuNd0exfPT8z8jKpyI3UPERzmXb5cGEKgIBqdfugLVN6mkEkkQrPZqaBAgtGEl7K7i2DIOSuB6F4uEIH7QJnHWauPTKkCmzHAUfTF2XP1xqJ0uejptusvYdgVEExd9Ugnh6YSqhmLmuQE0jgFSyUGr2hFjXGczVEx3UczQI1f1xYZuNGG1b2mbtm8yE0dOOTnZkxl
kite_access_token for YY0222: 5M0qN2o9jjiRjQ5KHYVzxYjw8nTH7p0A
AmiPy strategy
450
Program started successfully
Attempt: 1
Today's date: 2023-08-08 08:55:03.128100
Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x12a8871d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12a8871d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 298, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 165, in login_in_aliceblue
    getEncryptionKey = getEncryptionKey()
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 162, in getEncryptionKey
    response = requests.post( url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12a8871d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Attempt: 2
Today's date: 2023-08-08 08:56:11.661439
Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11236a750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11236a750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 298, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 165, in login_in_aliceblue
    getEncryptionKey = getEncryptionKey()
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 162, in getEncryptionKey
    response = requests.post( url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11236a750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Attempt: 3
Today's date: 2023-08-08 08:56:19.240091
Login Successfully
Session id for 929016: FnU5aWaKfymyWsKvx4T39ZrrYOqLij8ipdKp1thqRSDS57qUj9cP2R6VgCHth5P4mn5UfRQvFBFlQKucdlatANrETjpE340XOzfmobx0LbbN66D8s7qUoYmzvVVtSBQshDvab85BvMxoU1MATlpM3WjnY837FLzPtTYtttMMH2GGODXsi4EmMTur2UNiVsIxfozIyTZbPmGOh7d4azuFd00EpfmfUBTaYGihs0dhQsa7HuSjDy3JCbxJ0nkR0Avu
Login Successfully
Session id for 935325: Wli7fMG1ZaFs4ciCBEjEoI7ZOZIDlVg6We98ssjLiRSnk6REEylAzXLDHZDRuy1OJTEdWNsrV7X4rzCY1KlXaepmqM9TdgXTQqfi2IVMbkgunALv69f8DQDIDpK7L5JEButW8KrgTaBlWquRQ3lVQ82LUUQMlKjd0ITGQFoFKFtahm1ms13BZTLjW0JUhSJlgfmStFLyYON2HkQJslCjH1VYIiPvnBNxePGEMAhd97BcGb9vNrsHkstLZy8VE6jc
Login Successfully
Session id for 924446: npWDLBoMZxHmpTGpldGrMCir9yLCnriHnQY2eZqkmB8L1n6fXJabXhnlOaECjHPUHEJ9dhEuGXMDN6c0RnfhgOR7hUypqPXOX9W8mY68Fx00CL8dVYQk60HZT837rHXrgPC3sk0nWkFe5V8JZM5f0yOT5BqRx1Z4pRiuQnBgQVFljRDaIUkBLEzEHCJ3JR7as7FE7fmx88RXWBMINKf8P0GvugjJClkMChclbHuSf24drkeUqQcMRTcVX7CgdGU3
Login Successfully
Session id for 935347: gzE5mGarxDgeMpd97Dub5zDgjQ0EfzY2FPndYpR8uFh1VLFuCellKeteSDVcPfyikikq60KSYGhmWBrLbcNNikx6GklaVG5caCKuvqDsnWhCG9By1PCmpLheL4h7rXSNpgEDmVTGXX29QghOMk0kVlcYE8gaqrWT9DqiZay4q7Ya3tqAIsIY7Py9VhQoQrepdYyAMWQ9mKeL4opOednsnWpMUplrsh3Ve1xyxROHod28sl3EuRiY2W16LiNu2tzu
kite_access_token for YY0222: 9v2ZB6kcIO4ujITZ4ieIXfXf68nQLpYq
Program started successfully
Attempt: 1
Today's date: 2023-08-09 08:55:03.276332
Login Successfully
Session id for 929016: 3jEIx83zqsXFtn4NTK3zxpgc4UuvHGSYWT3JhZkM93IdpW3nZUNM4IIqc8DPMhiN2s4RyzIyUprsxUgKF2MpDXujltz3RVeLZnl5ftzHM2LzV4o7AAWq0oLbNvme0bQNUuCJHvB4heBkquh2WK7QSQltErYUXNA8aUQZ9tfNOSRZ1kPCCriyCzu1v62VsEnQCTHVTdrynut580lZjucipzADi34CUY3lZjazjUzqADCJyr05bR41uQeQlaLY9RRk
Login Successfully
Session id for 935325: ZxmDoYAdH5rT0fSl5LN3CZeHOLOygr5GDjlSNvovTJgPj24vOnpURxj0fCh9SjP0KMvsrBHN0X4iGXbCU2U3fgjEUZaHgMnaiSpm39ZKNLu9lRmrnjO1Uz2OkkgNP0SVPUeCSufFGh4gCx2f5Ggm9Bhzgg37Ub1HBq9gBezZsVcAkM5j0qvJCyEkvMHqxEzfXDaCzF1UfBoiEQqCQdG3sWzP3EqYelOy7JPqeg4jInPj2UPRJzQb6pKVoae0dJER
Login Successfully
Session id for 924446: 9Q4ViTG2fkvX6eVq0mpy31l6LLE2u0aKKPSbucJzWRWDJNqfyNH0qaGnVGBx2FJ1BroLD7mAI7Cm3WSMIKAAAsotz6fslH4JtJ43UW9d49JhODb0tEp2RvXfE1UOu5Ng54KKzEm9EIdjjFWSaW0uogcmXmuocPChvzoSYcWh9K4ga6SZ4srvolvbbrScJnXCVo2e56KDCPIoiLFEb1bNLL5IjCuUXqXiqJP3a6ZBR6N3aaT1fhgORQA2bgeOQRx3
Login Successfully
Session id for 935347: 57yIBCShn0h6bsEyZbxIGT8V5aHSsOyHUlWrCNixWjeJSSJmI5agmHjVXhBt8izWGzys2PlytE0zDxatiKuc0ltY8kryMNhtDCUBFBzOzL9ZhOh3xfXBj8QvtKXuTttqFY6cUiOtx564X8FUkbGfCkJ7rTHDuTM1YqAEmZshRoHW6yXpCaucmUWvzNEDhyCGWHmSniUKusPAJzVTjMhz2slSY49sY0lnmsym1AbCIfyHVjCWEFqs9nHog6ZrW3Ek
kite_access_token for YY0222: cSAgosR3xp2g5KNxTLhNxiiTvki3uMbU
Program started successfully
Attempt: 1
Today's date: 2023-08-10 08:55:03.250918
Login Successfully
Session id for 929016: goDkt2NGTvSdoXBoCKZ23jXo7jcoWIfH3SlT2jQzipyIu2jL86stQnrkbRuOP6i9LZXbQZIZruZPgt53KzVUv2Zn4F38ski1L6kvuILCrWl1pt6deAtk19eCxCcN1s4OkG3ssO4SuapN6CuR0oqcdEX6BpARRbPharC8ySs6yOdKLgxkVTdqZJDAVdmP0Y4bVUaKDCN1i0ZWfigZGCAqOniEjxQuYjQ6a0diQYlooUfybXjHf77Ce8JZAjaiEg5A
Login Successfully
Session id for 935325: ReVeW5FQInM8uy7M3QBhYL0FEtNVklNIlqOBOtsu8xEDCSFlQQrERntnY7g0v1fWVy89DOmUrjgq7br5lJXvAT4zFRfTpgKSFdUPPHkjGyUKurMDtWt6odC4C7I1r89A50RhsY5nfohEqNBlNhggXvH1XUlZzOb6NS0E9tgIUJutQg6GHRBJNCsTBNgyZUrnqWy61f1uTygtgKuA2tjtWOIP3XBOc41iJnT50OFstRcxq47iOfupUNjctGDKcJ4d
Login Successfully
Session id for 924446: rY87L1m1NX8JxtRRKgWOELm5ydti2Tr9I0nKG7nMuUkl1l8T5OB8mFF85UgPSYeDnR5QoqvGmXEnlJMqu4FsmUzykotyH7suCbW28i7437iIbRedX10YTVv7HWev9zNpONICY3vJah9gmhF2sFeZkIzyYp9H3miYre3gQ3qArGQE8NGjxlhm1DnJczdeg2XOeOydTaQEaDbUQyxJVo1c3nHkEjKT2kjWuN6nYfSaWCPHKzkkGSgHtePBbuHPrcrt
Login Successfully
Session id for 935347: TInsetY2n5tQI0aGF1WgimQJRmhR934YKj098GIyqTlP9Z6IYJV3FKPVbi02yk6x2LYWjS9Zu8kCZYadDkhvmAQMqdCMqDCKKWyC794EO1N1JigLY1MQBnCx8IaDZNVbZcGIbCFunh8ja0gpZ0d7JUt6Cke4kxMrihVtBEg6nU934T9H276Uf8PN311XL7TGSxWgBGqTSdJ9V1brQCAc1ADZTMynhC10goXZeS5uK3Hh7pCaLgHxBIofisfshX4D
kite_access_token for YY0222: 3LgZJSfdz8bLOCXy1Oy9SoJnqqx6lQHF
Program started successfully
Attempt: 1
Today's date: 2023-08-11 08:55:03.441159
Login Successfully
Session id for 929016: jXnaqhq27qHTxYvMafGSLCckplgNEyldfBdVKUgPll0MJp1Ylzdjc1bC0gtNmcZ502EvzBabti3PgfRCcE5hVmlSzW80TKIxalOge4hnBIZ3iCS0vbde6p1PeOaj2CzrxiyaHBv2gEq5hkY0WU1WnMAhrrkEWmsQCD6Pq6bggrex6mTKPOjAhSlvMo6unibHxe7u39b6rCzKAxdB5HmUAlLKUdTOleA420OBJt5aS49K6tRopVeP6qKXTPoYSGVt
Login Successfully
Session id for 935325: BgqcFIadCsv2yXkWiKPKtPsMcdllfIyHP1r3zP8Y4qMSM9qqI0uqnikUDO45WWntVrzuMfUA9RFbJ7NE9dkUNBBst7HIcSVQ5Wd3Hcsr3fVrGXZaisBiC211F9u3XulGWQ8ZiHoToRTOLB1H97Hex6qXqpSdccfKlHdmzINx2FxKtGm52nj5oGP1kVojCLOOB1MuZEDVhxG2mkkAJZNy9yK7vulChkjWE35ABU8ygHEZSAxe0eKhCeRkepfORQK9
Login Successfully
Session id for 924446: d74ln0QeaTnIPQmkJkUYJ62BRuoSTW9ZJUB65hivAulZRiO3a3pXppDN6MMWcLGmmnfWuRO9bei9lt2hTUYvE6vfmvqKVqmepALPAXGG0lCTgqTn9I7ROJxz7bbZSBbg8LQGf1QktjATkzeMc5A0suO2mjo4WXhVO6vOWaaJI2JMOFl4tfvq7P2xSOn9TorT9AsysOSKNgmkg3qI6X7Ld3bvKp7tsjKIQ2U5buoItgjUX7svxMyQjznh7G6ZIfyz
Login Successfully
Session id for 935347: dsn4xIzSPkPbtrJFElRm1TXv2qIP52TyYj6ZX7a4IlsdKlCc13L5ieFcQqM5PlxK9XVb9WIhKbUEcR8zP30ReKyzZozgNttBVqXvx9AtxUlopj9LOuPuD3pyusK7D9onbGrj0D2jusA1R9tUC4LiadH1kAiKn48tXq87NOT9hcrNQ7qOg5fVqvbQW680sbrYUk4pzB7aovFhKLEyQEqk4uS87F230hTvfkyXSu0N8KRWl6bCq9i5lf4QV9Q9qU6q
kite_access_token for YY0222: VQEE6QRLISfQY23XVT8ZfbRUne7eiZxD
Program started successfully
Attempt: 1
Today's date: 2023-08-14 08:55:01.898546
Login Successfully
Session id for 929016: JCmRgCxtTDddRCZIDP7EXeeYOrg22Eo7heUM93MLdfhiY0DSuL3YAsgaKuJ73U7YlPG6T7DTrmuS1zHAMi3tEhkoRlnckRxJXYcE9QG9NCXHCJTZTPibNi6KYvJTVZ0rWVBZfvQVoNN53YPBr5WC3fHptZBbzgLBf8X0bs9J6uiAVBolxXLmXHyOdUi3nMf8i7esSOJsvVeAUBlTlk2VV3zVBB8lSVY3Ms35Hy5Ud6gtQM892lDMWOuY3QW12zjV
Login Successfully
Session id for 935325: XkxKWfAVBcvZK1VZaUEuZMFb9HH6X6C1cKFWegzjCNsNdZ8iJagyGMKRSVVrAx8l884f4IlH0rUDv1XHPCBcHV0rlfL7IU4UasKacr8kuUqIVsnyLfTVK9aeWjVhBPAtxrA559luKH9AyIk74JTY34nDF20inuGULrb235GQp4YU3b9RbkKcKUpBnzSE3B3llrJIVihOsabtNszTb816tO0dhBq2DJX8NskyFSqmFlfx5KDV0tcfkezEqPtODOlA
Login Successfully
Session id for 924446: AczPVRcezH6m4beT1J6kC2Sq0FUiBHAdWknKAzBu8LhDCT5Bm3E0zXRrDUd3oHC3VEPYHJRsrcsCJe8aLqcPcdj3UnoOTWKt7HF19VRO16Bt4jlLhRzftYaf7jmThbFEdd9MS9SrIlUGpAP8CzK1hT6vHgHU64izBcao70Q3QLi0EVyfS6bi1jVoymmUuoMOqcezqXQOQofTaaA1MTZVzLcrNSDNxHDoMSdXs1Um0mPRrJinUSC3fEagESbWYWg2
Login Successfully
Session id for 935347: cW3sjknNBKaOnYUSzzgfO7vzyk9HjoddE1FsY1TRndXMJPM3muQVJ7be6BkROKcxz6m8TGZYl6iA5mMKq8lgWDF4PestYFYsPSgHtDDRxtH3lAJELdOuadCDHKWR0gNrNSQpDyu1IlLy3i13AntWE3WuviQZ9aJRkJeKpSEn495fLyLEqGeh3etaseWR9ZVZ0OHN8n9iRkbFyfYDyfahBDPa7PS8UbZdy0k6vYbNseSlT9hXkeqtoLxryfx6t4Kv
kite_access_token for YY0222: TM5qmwgU5les8pFHak7Za6lELvzvyFwb
Program started successfully
Attempt: 1
Today's date: 2023-08-15 08:55:02.725432
Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1346ee9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1346ee9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 305, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 172, in login_in_aliceblue
    getEncryptionKey = getEncryptionKey()
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 169, in getEncryptionKey
    response = requests.post( url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1346ee9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Attempt: 2
Today's date: 2023-08-15 08:56:09.924898
Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x12c6ab910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12c6ab910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 305, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 172, in login_in_aliceblue
    getEncryptionKey = getEncryptionKey()
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 169, in getEncryptionKey
    response = requests.post( url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x12c6ab910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Attempt: 3
Today's date: 2023-08-15 08:57:17.046383
Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x118dcfa10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x118dcfa10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 305, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 172, in login_in_aliceblue
    getEncryptionKey = getEncryptionKey()
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 169, in getEncryptionKey
    response = requests.post( url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x118dcfa10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Attempt: 4
Today's date: 2023-08-15 08:58:24.482423
Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11b0df450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b0df450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 305, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 172, in login_in_aliceblue
    getEncryptionKey = getEncryptionKey()
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 169, in getEncryptionKey
    response = requests.post( url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11b0df450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Attempt: 5
Today's date: 2023-08-15 08:59:31.607890
Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11e418850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11e418850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 305, in <module>
    user_details = login_in_aliceblue(user_details)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 172, in login_in_aliceblue
    getEncryptionKey = getEncryptionKey()
                       ^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 169, in getEncryptionKey
    response = requests.post( url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /rest/AliceBlueAPIService/customer/getEncryptionKey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11e418850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
The script has some errors. Please Check !!!
Attempt: 1
Today's date: 2023-08-16 08:55:04.366173
Login Successfully
Session id for 929016: C2JLukT8bJYAldruyhf6kEa568BLySuUTyeBfsfxq3Ur5pFvW8tXCPrY8hB1II8c5stgoxo41k8yWLd8EYsyfjaUOT381J5SfmVZcAU1TUYqvmrP4IkPlVBggSRNbUFiEM81bhztdt7GSvB4uqYnV01L4EUAt5Zzed8xrpcRNT3fUICpDOknjeLYEZztihRK7RJshFCHE7t500cNdF3GXi8n5cjz00Yjq9hUZBNHVG6QYD9d2Pf9jeZuazEQS5mY
Login Successfully
Session id for 935325: zgGbliSIbvma1vjpUuUz4ykyoZ6FeTZYAGXmZpBGzi2FvBI3A3au0ZrrZKNgZrenO9gWXI0xLKfhguepouY4srG3PCKSmaobvucVhiCZBUerDyoc6qfSF5i1UPFlPxjm6uqcpzSlzl4p7WQXsVK5Vpsd9jXukLYCNm8tNTbitdlU33qpP5zvvelFfYhG3gGQmzMAJJ7UntQUt2z2aVY5zGvCA1yLrpxQfG0UuORZBxyImEFZcqzojIvZzIWkBl3j
Login Successfully
Session id for 924446: 5JsDJyJADDNMAo978akCujLsiUtzEakoi9eQW6vbxSili0iJI1mjtKdZGAF5EN02fekGq1eKVeLelyTUpNgmsXSp9i5TSniTr0FOAjAtC3u5qXPeB15XmqnWKhJFmsXkIRmKy93iKEvtkZGjN9WZP3f8f227IorI2hv7bTlJLBaOXNZbKpSrddo6gNR177x4FN6b8jJhvcjenKPjsWS0MdETucyjG0L4kdcuaaOWDqt7lAzDP9fWcWE68esEV8Bc
Login Successfully
Session id for 935347: eR2l6JvTqRZZeqt9ioOLUoA1qY4pLZdo5PY6SSjRhxVI1COVDhLqlUcnu4dLYGQgEu1PW2q7j3nKHVITGZ2vGMryF83zTMm7VtPULg6OD1kC5xZuKnn2r0QIook07C0OJlDRjSGZDCl7uGWtOZ66OhaT6apM8MIEBDkObK2XbaBqIrLHP7axDm4ghxqhDTGkcZBdSSmJ52dktTsd7fAIYF0T5jB84Zq9VOnXs77QAyKPajRI2zWNSagz3bWIuOWx
kite_access_token for YY0222: gxryTzBzAjKfmyxXGkVPry2VGbM7mCn4
Program started successfully
Attempt: 1
Today's date: 2023-08-17 08:55:03.622213
Login Successfully
Session id for 929016: GBlBSHuktFpDWZQLCVxUNVQrzMcO8yMR654GVEIQBS6eaxzYP9lB98ZJgaYLjN3hZzmxYSk6UZz7LM3Hee1TDGs0KXL5vMaMEHix7oCmjnQrxSIXIXN2scdstBlxpRtbdzZE0eG8aQWLiGALkaWnXYufTQWukVZKpuEZY1na7YO8gSlsdHR2VuQrcfhnJBpCA6FJIRBtgKxFCrGsIujXmrvlGWX00QHFVC352mxKqqSToiD9Ob1Yp0VW6D2upKuA
{'Afternoon': [{'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:11:14.669747', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:11:15.469026', 'strike_price': 19200, 'tradingsymbol': 'NIFTY2381719450PE'}], 'Morning': [{'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:36:16.365064', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:36:17.149314', 'strike_price': 19200, 'tradingsymbol': 'NIFTY2381719200PE'}, {'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:37:59.685708', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:38:00.406177', 'strike_price': 19200, 'tradingsymbol': 'NIFTY2381719200PE'}]}
Login Successfully
Session id for 935325: RNu7V351B5buRMIeSVzBPQ72VjrVWFTBieWRtDMpuoEeieg4XDL6V6BL53dFvR0PTu8e0C00FOpudJ22q7MFL95ilYd8TjG4aefNLyuRpUk9MoGX4jNMMov0ImHRr6NjqTJUgnla942KtvArXFmnngF9GlbuIh1VNFBAKgbjj58ULQ7uzdPODaC2xBYh0xkkqUOx2GD9Q0HVRmbvbeGZ9GbxImCSvQu8aBUuCHWKEkWMX9VnzGuUh6SOCJNevD3n
None
Login Successfully
Session id for 924446: 2RRuA8GriOEG1oILzNZBuC83BTadF59l2nlH1FQoVDB7y5JKlazabkEXVKGssjVFC98JHqsHlhrGd6EHhyiJOTtLAuNzgTZWeKycLKr0cZ5ooj3uUYx4WGhTXSts9oBMl2K5CTK6Tm9yimGPnKC2fRsKPadTZgfeGybDEcU8YmCdWmL8UJtEpyQaVeC4qtqUMWfMlrIjLmpfcNUMh8qFggobzOdIbKneJV8Jzl6J3xulcz3pVo9biKoYCTHmrEh4
None
Login Successfully
Session id for 935347: WYLmqyZYa0SB4hJmsQCclo97Vdn7DQ5xLdRpWeoHsxgjcBr1x6yIPGT2WcF8x1NcSL9X1lWRKbUh63lVIXuW23QAEXOgAU9gFdyTMjsHUv3tmhYvqVtfPupiVr5LMKOvUly7Jq1HLm8RkzymkBmUrGU4jeIsNCqzszTOW8ohs5kb7NFjSsLqQspODIFVivCkWNu4iFeErKJj3FmWgHWoYEPuWCOAqFStIABH4Q3SxVkqg0kaFrbmBQepPLhkxWce
None
kite_access_token for YY0222: ZeRyt2C5jaoAfvKPbS51BNn4mtYHD2Eq
{'Afternoon': [{'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:11:14.669747', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '00.00', 'timestamp': '2023-08-16 18:11:15.469026', 'strike_price': 19200, 'tradingsymbol': 'NIFTY2381719450PE'}]}
Program started successfully
Attempt: 1
Today's date: 2023-08-18 08:55:03.474275
Login Successfully
Session id for 929016: sFsiglA4Pzu3g1LS9LsXdORLC37XT9KeMmLN8AcLBLZfQNhSFfUBxzuN5uQF2K0Rc6JMUeYfMIFoLSI7zt5f7IpSnSRzIOzcX8SaHO7hhjt2FRm1b9gjjpRyx3lV8rW1T2crrEABX7oyGKIhWRhoQpfEASQ0fNq0FsMXnYgl8Prh7VZ29pYuNF8eQpPTXCrBjhMACzGAofP2ox8dbzE7ZzrKcrGuJdYTUSEAYgLYGmxLcRSbPUXPodTqVhG0mDnS
{'Afternoon': [{'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '19483.9', 'timestamp': '2023-08-16 15:15:14.669747', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BULLISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '01.75', 'timestamp': '2023-08-16 15:15:15.469026', 'strike_price': 18950, 'tradingsymbol': 'NIFTY2381718950PE'}], 'Morning': [{'direction': 'BULLISH', 'margin_used': -99392.58, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '19459.22', 'timestamp': '2023-08-17 09:18:09.670285', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BULLISH', 'margin_used': -45.01, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '00.95', 'timestamp': '2023-08-17 09:18:10.318076', 'strike_price': 18950, 'tradingsymbol': 'NIFTY2381718950PE'}]}
Login Successfully
Session id for 935325: BEQVylzYr1imPU6UN2gUsGMovRFVjYEAd9rgO6nYe03uWv78l7UP5PsjTCHX7aFk2nFvTYsgoAddloXYmvSCFQseEnXyeOa18lGUAVetQ6Ih4vAoGKhutekgjC9jxeRjiFlCYFSWh8sVVmZBVXG1psu10SWgtIKhuq4pcVS619Bnok3kACBm23tNKoOOH7EyCKXsfkSq3MYBVcKApulMgSiWjLa5Lg0kp4jy6fKnl6U4hQth1O7m1QhBZVLzjbS7
None
Login Successfully
Session id for 924446: f7KePqcWNmmmWdgVBrP4sPjh147y5PBPCyFUsq6kNB8ibUD1Ysp0CbeHEdM53Vud3diIt4tG2xakPEaqWnbYyldqrfVKY5ScgW50IHxLrN8VWmsFaYgsByo1bycKGi9WZspH7rzPTUR5Y2bF8Pbz0JESR31hJnOLJQUcBXJofqS0Sahim8LvpUaQy1KPjd9zI1Sxaf8eKhc4xzrh708tzJ7KdX0Ee5l89BSJn3fLoofXxoFdcN6tpjDnWUlJikJY
None
Login Successfully
Session id for 935347: maWGidKFGtgE7vGffjM5yo6Y5NvsMcmR0nulzA8N5iMNYqBtRyxO7rhV856c88Xh8Neb1DKn14VESSRVuglBJS5bChgJZ5HV22pCfbpLJC2dYHKVnoEQ2lFEkpdkG7vgGzYAVbEMNLblxt2EGYu3dk7VuD14Ltp3z0ZFUHCUtAPxnhrO3gSKIxjTyk2r32uN3ajuE5Are3R8EDhQFgNkaPKHomv6VRbqOTBmStn9y0OUFRhf8k0pOjQQPrqYX6Rm
None
kite_access_token for YY0222: C462xyhTHBs65ghisB4LXiv82A6rhXyx
{'Afternoon': [{'direction': 'BEARISH', 'margin_used': 1003998.58, 'trade_type': 'Afternoon', 'qty': 450, 'avg_prc': 19393.2, 'timestamp': '2023-08-17 15:15:14.612100', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BEARISH', 'margin_used': -761180.8, 'trade_type': 'Afternoon', 'qty': 450, 'avg_prc': 20.37222222, 'timestamp': '2023-08-17 15:15:15.042409', 'strike_price': 19600, 'tradingsymbol': 'NIFTY2381719350CE'}]}
Program started successfully
Attempt: 1
Today's date: 2023-08-21 08:55:03.168294
Login Successfully
Session id for 929016: Jg7iyQQWXmyaeRylK9UKdPWJxZAY2squR1AjsFcIAXGYM3QRBZjCvz3PdQA2LbnNom0dvjgEC30XZzZ1ZTe6mX9kVV1UNHQnnCM3y0E1KY3qy0czAXBFDbJnTvF1oaZcQvdcDPDVId239VrVP5Lf9QAkEcjv2ZlEbnj3n9fzxZrUHArZ4UTGMVESS26W70nP1DOXGbQQ33WEHPTXTOE7B749yZY1b8q22uxnsWHhOKn7Zl3tFl6ZsjxgqzmQ8bQF
{'Afternoon': [{'direction': 'BEARISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '19388.50', 'timestamp': '2023-08-16 15:15:14.669747', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BEARISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '22.70', 'timestamp': '2023-08-16 15:15:15.469026', 'strike_price': 18950, 'tradingsymbol': 'NIFTY2381718950PE'}], 'Morning': [{'direction': 'BEARISH', 'margin_used': -99392.58, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '19323.45', 'timestamp': '2023-08-17 09:18:09.670285', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BEARISH', 'margin_used': -45.01, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '12.25', 'timestamp': '2023-08-17 09:18:10.318076', 'strike_price': 19600, 'tradingsymbol': 'NIFTY2381718950PE'}]}
Login Successfully
Session id for 935325: Q2zkaLWh4VSXjEBodp9mCH9dSdkA6vV3AZDFggaKcMXA9N9a8xuFkaraysaW3XfjO1SEWpPC6qDBazluJ1jZUMNmvfq7zczxtDQ42l5rD5YbYAtEoPvMPk5qrfATeezJoCfxQGuf2RxWKibUYekPcjLtIZ6ue5IALhZx1ZQy5OT7IzWTd3EuLEJmy996LFRJVBqZEGeVqiy7NzF0T2fo1uDjEYEgRHYyyJ2Pz1sHaB5dpRAeOvI1LxhJMVqXsXaS
None
Login Successfully
Session id for 924446: Rd8k28Jf5m0c4ic49IHTxaIZ4HsYMX0lXgsvsMi4UBtYjfTMRjrC1HPnBN1Xbjtn7kxdjGevk34R79o7tbGlxl2H2PN8eptgFjkhRZAIN0h4Qd90N1r2FIXcC5ZD3NaAFIDNknpY5mKn11ELTeXyjanCkHz9YMgYMY6A1ISdO5YrZm3AdlRgLRDtt2aMjuWShT4MBbyFRFCGLsdiLG2RdTW8krtGl2IhotdNID2Lo0G4aeInjcvhrGfJcdBjA2PX
None
Login Successfully
Session id for 935347: q8sB4ikmCFEsb4HASfzblqWsKbU6pbZmxDIj8uk2VXL9qr9rsHP3ptr5mMLMb433ZZRjcWtjyug5FCZZRFpsb3suAcsaQEPTQzuOaRaPnAR2LpLMCMTiKCKGcBNfTd075LK4BbEl0hayAS2kWTOkdNlab2g4XQXLIBO24ClBcUTELnfVXSuUgG0MoinEKvJv2uOdLSv1TTaSVXRu2rQ0P5SHAM64mIhWcfNUgmY8cSgs1UK0zlFyVnxRBHFSQ46J
None
Traceback (most recent call last):
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 323, in <module>
    kite, user_details = login_in_zerodha(user_details)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/Documents/TradeMan/Utils/DailyLogin.py", line 254, in login_in_zerodha
    login_id = WebDriverWait(driver, 10).until(lambda x: x.find_element(By.XPATH, '/html/body/div[1]/div/div[2]/div[1]/div/div/div[2]/form/div[1]/input'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/traderscafe/miniconda3/envs/tradingenv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   undetected_chromedriver             0x00000001034096b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x0000000103400b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000102fbe616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x0000000103001e0f undetected_chromedriver + 712207
4   undetected_chromedriver             0x00000001030020a1 undetected_chromedriver + 712865
5   undetected_chromedriver             0x00000001030439a4 undetected_chromedriver + 981412
6   undetected_chromedriver             0x000000010302603d undetected_chromedriver + 860221
7   undetected_chromedriver             0x0000000103040e76 undetected_chromedriver + 970358
8   undetected_chromedriver             0x0000000103025de3 undetected_chromedriver + 859619
9   undetected_chromedriver             0x0000000102ff3d7f undetected_chromedriver + 654719
10  undetected_chromedriver             0x0000000102ff50de undetected_chromedriver + 659678
11  undetected_chromedriver             0x00000001033c52ad undetected_chromedriver + 4657837
12  undetected_chromedriver             0x00000001033ca130 undetected_chromedriver + 4677936
13  undetected_chromedriver             0x00000001033d0def undetected_chromedriver + 4705775
14  undetected_chromedriver             0x00000001033cb05a undetected_chromedriver + 4681818
15  undetected_chromedriver             0x000000010339d92c undetected_chromedriver + 4495660
16  undetected_chromedriver             0x00000001033e8838 undetected_chromedriver + 4802616
17  undetected_chromedriver             0x00000001033e89b7 undetected_chromedriver + 4802999
18  undetected_chromedriver             0x00000001033f999f undetected_chromedriver + 4872607
19  libsystem_pthread.dylib             0x00007ff804cb71d3 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff804cb2bd3 thread_start + 15

Attempt: 2
Today's date: 2023-08-21 08:55:31.216187
Login Successfully
Session id for 929016: Jg7iyQQWXmyaeRylK9UKdPWJxZAY2squR1AjsFcIAXGYM3QRBZjCvz3PdQA2LbnNom0dvjgEC30XZzZ1ZTe6mX9kVV1UNHQnnCM3y0E1KY3qy0czAXBFDbJnTvF1oaZcQvdcDPDVId239VrVP5Lf9QAkEcjv2ZlEbnj3n9fzxZrUHArZ4UTGMVESS26W70nP1DOXGbQQ33WEHPTXTOE7B749yZY1b8q22uxnsWHhOKn7Zl3tFl6ZsjxgqzmQ8bQF
{'Afternoon': [{'direction': 'BEARISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '19388.50', 'timestamp': '2023-08-16 15:15:14.669747', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BEARISH', 'margin_used': 0.0, 'trade_type': 'Afternoon', 'qty': 100, 'avg_prc': '22.70', 'timestamp': '2023-08-16 15:15:15.469026', 'strike_price': 18950, 'tradingsymbol': 'NIFTY2381718950PE'}], 'Morning': [{'direction': 'BEARISH', 'margin_used': -99392.58, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '19323.45', 'timestamp': '2023-08-17 09:18:09.670285', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BEARISH', 'margin_used': -45.01, 'trade_type': 'Morning', 'qty': 100, 'avg_prc': '12.25', 'timestamp': '2023-08-17 09:18:10.318076', 'strike_price': 19600, 'tradingsymbol': 'NIFTY2381718950PE'}]}
Login Successfully
Session id for 935325: Q2zkaLWh4VSXjEBodp9mCH9dSdkA6vV3AZDFggaKcMXA9N9a8xuFkaraysaW3XfjO1SEWpPC6qDBazluJ1jZUMNmvfq7zczxtDQ42l5rD5YbYAtEoPvMPk5qrfATeezJoCfxQGuf2RxWKibUYekPcjLtIZ6ue5IALhZx1ZQy5OT7IzWTd3EuLEJmy996LFRJVBqZEGeVqiy7NzF0T2fo1uDjEYEgRHYyyJ2Pz1sHaB5dpRAeOvI1LxhJMVqXsXaS
None
Login Successfully
Session id for 924446: Rd8k28Jf5m0c4ic49IHTxaIZ4HsYMX0lXgsvsMi4UBtYjfTMRjrC1HPnBN1Xbjtn7kxdjGevk34R79o7tbGlxl2H2PN8eptgFjkhRZAIN0h4Qd90N1r2FIXcC5ZD3NaAFIDNknpY5mKn11ELTeXyjanCkHz9YMgYMY6A1ISdO5YrZm3AdlRgLRDtt2aMjuWShT4MBbyFRFCGLsdiLG2RdTW8krtGl2IhotdNID2Lo0G4aeInjcvhrGfJcdBjA2PX
None
Login Successfully
Session id for 935347: q8sB4ikmCFEsb4HASfzblqWsKbU6pbZmxDIj8uk2VXL9qr9rsHP3ptr5mMLMb433ZZRjcWtjyug5FCZZRFpsb3suAcsaQEPTQzuOaRaPnAR2LpLMCMTiKCKGcBNfTd075LK4BbEl0hayAS2kWTOkdNlab2g4XQXLIBO24ClBcUTELnfVXSuUgG0MoinEKvJv2uOdLSv1TTaSVXRu2rQ0P5SHAM64mIhWcfNUgmY8cSgs1UK0zlFyVnxRBHFSQ46J
None
kite_access_token for YY0222: TcHQRv8XBKbm8PaonQOCbB1Ynaf4sIyZ
{'Afternoon': [{'direction': 'BEARISH', 'margin_used': 1003998.58, 'trade_type': 'Afternoon', 'qty': 450, 'avg_prc': 19393.2, 'timestamp': '2023-08-17 15:15:14.612100', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BEARISH', 'margin_used': -761180.8, 'trade_type': 'Afternoon', 'qty': 450, 'avg_prc': 47.8, 'timestamp': '2023-08-17 15:15:15.042409', 'strike_price': 19500, 'tradingsymbol': 'NIFTY2381719350CE'}], 'Morning': [{'direction': 'BEARISH', 'margin_used': -329354.28, 'trade_type': 'Morning', 'qty': 450, 'avg_prc': 19319.8, 'timestamp': '2023-08-18 09:18:28.887882', 'strike_price': '0', 'tradingsymbol': 'NIFTY23AUGFUT'}, {'direction': 'BEARISH', 'margin_used': 168456.6, 'trade_type': 'Morning', 'qty': 450, 'avg_prc': 26.0, 'timestamp': '2023-08-18 09:18:29.141319', 'strike_price': 19600, 'tradingsymbol': 'NIFTY2382419600CE'}]}
Program started successfully
